[package]
name = "random-read-file"
version = "0.1.0"
authors = ["zdd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_xorshift = "0.2.0"
memmap = "0.7"